# Default config
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  username: root
  password: 'mysql'


# Development
development:
  <<: *default
  database: artists_dev


# Test
test:
  <<: *default
  database: artists_test


# Production
production:
  <<: *default
  username: root
  password: 'meiya'
  database: artists_pd